include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'

variables:
  MANIFEST_PATH: 'examples/org.gnome.Adwaita.Demo.json'
  FLATPAK_MODULE: 'libadwaita'
  FLATPAK_BUILD_DIR: build

stages:
  - build
  - publish

api-visibility:
  stage: build
  before_script: []
  script:
    - lint/api-visibility.sh

doc:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: build
  tags:
    - flatpak
  variables:
    MESON_ARGS: >-
      -Dbuild-tests=false
      -Dgtk_doc=true
      -Dintrospection=disabled
  script:
    - flatpak-builder --user --disable-rofiles-fuse --stop-at=${FLATPAK_MODULE} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}
    - flatpak build ${FLATPAK_BUILD_DIR} meson --prefix=/app ${SHARED_MESON_ARGS} ${MESON_ARGS} _build
    - flatpak build ${FLATPAK_BUILD_DIR} ninja -C _build libadwaita-1-doc
    - mv _build/doc/html/ _doc/
  artifacts:
    paths:
      - _doc

build-flatpak:
  extends: '.flatpak'
  stage: build
  before_script: []
  variables:
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    APP_ID: 'org.gnome.Adwaita.Demo'
    BUNDLE: 'org.gnome.Adwaita.Demo.flatpak'

abi-check:
  # See https://sourceware.org/bugzilla/show_bug.cgi?id=27267
  image: fedora:33
  stage: build
  variables:
    DEPS: libabigail git gcc meson pkgconfig(gtk4) vala gobject-introspection
    LAST_ABI_BREAK: "c6ded459e635154ec8b8e2c175b1937f9618fd01"
  before_script:
    - dnf -y update
    - dnf -y install @development-tools redhat-rpm-config dnf-plugins-core $DEPS
    # See https://sourceware.org/bugzilla/show_bug.cgi?id=27269
    - rpm -Uvh --oldpackage https://kojipkgs.fedoraproject.org//packages/libabigail/1.7/2.fc33/x86_64/libabigail-1.7-2.fc33.x86_64.rpm
  script:
    - ./.gitlab-ci/check-abi ${LAST_ABI_BREAK} $(git rev-parse HEAD)

refresh-doc:
  stage: publish
  only:
    refs:
    - 'main'
  script:
    - "curl -X POST -F token=${PAGES_TRIGGER_TOKEN} -F ref=pages https://gitlab.gnome.org/api/v4/projects/14079/trigger/pipeline"
